### ISSUE TITLE
Issue about speech dataset

### ISSUE THREAD

**Issue by cky-lab** [Magmaw/Magmaw#1]
There are many datasets in the Edinburgh DataShare, i wonder which dataset was used for training and testing?
https://datashare.ed.ac.uk/handle/10283/2791

**Comment by juc023** [comment]
Thanks for your interest!
Here is a link for the dataset: [https://datashare.ed.ac.uk/handle/10283/2791](https://datashare.ed.ac.uk/handle/10283/2791).

**Comment by cky-lab** [comment]
> Thanks for your interest! Here is a link for the dataset: https://datashare.ed.ac.uk/handle/10283/2791.

Thanks for your reply. 
But you posted the same link as i have given in the issue. In fact, there are many datasets in the link, such as clean_trainset_28spk, clean_trainset_56spk, noisy_trainset_28spk, noisy_trainset_56spk. I wonder which dataset was used.

**Comment by juc023** [comment]
Here are more details.
- 10K training samples from clean_trainset_28spk
- 800 test samples from clean_testset_wav
After downloading, we downsampled the sampling rate to 16 KHz.

**Comment by cky-lab** [comment]
Thanks for your help.
Could you please provide the prepocessing code for the speech dataset if possible ? I wonder the detail procedure about how the speech signal are processed into the dataset.

**Comment by cky-lab** [comment]
> Here are more details.
> 
> * 10K training samples from clean_trainset_28spk
> * 800 test samples from clean_testset_wav
>   After downloading, we downsampled the sampling rate to 16 KHz.

I find that the second dimension of the test dataset you provided is 16384.
So the size of the test dataset should be 800*16384 and the size of training dataset should be 10000*16384 ?
If the sample rate was set to 16 KHz, the sampling time of each audio should be 16384/16000=1.024s ?

**Comment by juc023** [comment]
I just uploaded a code for preprocessing.
Please refer to [preprocess_speech.py](https://github.com/juc023/Magmaw/blob/main/data/preprocess_speech.py). This will generate train.pkl and valid.pkl. Please also make test.pkl by editing the code.
